device:
    type: rest
    resource: Display\PushBundle\Controller\DeviceController
    prefix: /api

message_type:
    type: rest
    resource: Display\PushBundle\Controller\MessageTypeController
    prefix: /api

backend:
    resource: Display\PushBundle\Controller\BackendController
    type:     annotation
    prefix:   /backend