<?php

namespace Display\PushBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    /**
     * @return array|Message[]
     */
    public function getPendings()
    {
        $dql = 'SELECT m, mt
                FROM DisplayPushBundle:Message m
                JOIN m.messageType mt
                WHERE m.isPending = :is_pending';

        return $this
            ->getEntityManager()
            ->createQuery($dql)
            ->setParameter('is_pending', true)
            ->getResult()
        ;
    }
}
