<?php

namespace Display\PushBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PushRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SendingRepository extends EntityRepository
{
    const STATUS_QUEUED = 'queued';
    const STATUS_DELIVERED = 'delivered';
    const STATUS_FAILED = 'failed';

    /**
     * @param Device $device
     * @param Message $message
     * @return bool
     */
    public function wasSent(Device $device, Message $message)
    {
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'SELECT 1
                FROM push_sending s
                WHERE s.device_id  = :device_id
                    AND s.message_id  = :message_id';

        return (bool) $conn->executeQuery($sql, array(
            ':device_id' => $device->getId(),
            ':message_id' => $message->getId(),
        ))->fetch();
    }
}
