<?php

namespace Display\PushBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PushRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SentRepository extends EntityRepository
{
    const STATUS_QUEUED = 'queued';
    const STATUS_DELIVERED = 'delivered';
    const STATUS_FAILED = 'failed';

}
